// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package core_network

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/networkmanager"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/networkmanager/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/networkmanager-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.CoreNetwork{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetCoreNetworkOutput
	resp, err = rm.sdkapi.GetCoreNetwork(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetCoreNetwork", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.CoreNetwork.CoreNetworkArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.CoreNetwork.CoreNetworkArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CoreNetwork.CoreNetworkId != nil {
		ko.Status.CoreNetworkID = resp.CoreNetwork.CoreNetworkId
	} else {
		ko.Status.CoreNetworkID = nil
	}
	if resp.CoreNetwork.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CoreNetwork.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.CoreNetwork.Description != nil {
		ko.Spec.Description = resp.CoreNetwork.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.CoreNetwork.Edges != nil {
		f4 := []*svcapitypes.CoreNetworkEdge{}
		for _, f4iter := range resp.CoreNetwork.Edges {
			f4elem := &svcapitypes.CoreNetworkEdge{}
			if f4iter.Asn != nil {
				f4elem.ASN = f4iter.Asn
			}
			if f4iter.EdgeLocation != nil {
				f4elem.EdgeLocation = f4iter.EdgeLocation
			}
			if f4iter.InsideCidrBlocks != nil {
				f4elem.InsideCIDRBlocks = aws.StringSlice(f4iter.InsideCidrBlocks)
			}
			f4 = append(f4, f4elem)
		}
		ko.Status.Edges = f4
	} else {
		ko.Status.Edges = nil
	}
	if resp.CoreNetwork.GlobalNetworkId != nil {
		ko.Spec.GlobalNetworkID = resp.CoreNetwork.GlobalNetworkId
	} else {
		ko.Spec.GlobalNetworkID = nil
	}
	if resp.CoreNetwork.NetworkFunctionGroups != nil {
		f6 := []*svcapitypes.CoreNetworkNetworkFunctionGroup{}
		for _, f6iter := range resp.CoreNetwork.NetworkFunctionGroups {
			f6elem := &svcapitypes.CoreNetworkNetworkFunctionGroup{}
			if f6iter.EdgeLocations != nil {
				f6elem.EdgeLocations = aws.StringSlice(f6iter.EdgeLocations)
			}
			if f6iter.Name != nil {
				f6elem.Name = f6iter.Name
			}
			if f6iter.Segments != nil {
				f6elemf2 := &svcapitypes.ServiceInsertionSegments{}
				if f6iter.Segments.SendTo != nil {
					f6elemf2.SendTo = aws.StringSlice(f6iter.Segments.SendTo)
				}
				if f6iter.Segments.SendVia != nil {
					f6elemf2.SendVia = aws.StringSlice(f6iter.Segments.SendVia)
				}
				f6elem.Segments = f6elemf2
			}
			f6 = append(f6, f6elem)
		}
		ko.Status.NetworkFunctionGroups = f6
	} else {
		ko.Status.NetworkFunctionGroups = nil
	}
	if resp.CoreNetwork.Segments != nil {
		f7 := []*svcapitypes.CoreNetworkSegment{}
		for _, f7iter := range resp.CoreNetwork.Segments {
			f7elem := &svcapitypes.CoreNetworkSegment{}
			if f7iter.EdgeLocations != nil {
				f7elem.EdgeLocations = aws.StringSlice(f7iter.EdgeLocations)
			}
			if f7iter.Name != nil {
				f7elem.Name = f7iter.Name
			}
			if f7iter.SharedSegments != nil {
				f7elem.SharedSegments = aws.StringSlice(f7iter.SharedSegments)
			}
			f7 = append(f7, f7elem)
		}
		ko.Status.Segments = f7
	} else {
		ko.Status.Segments = nil
	}
	if resp.CoreNetwork.State != "" {
		ko.Status.State = aws.String(string(resp.CoreNetwork.State))
	} else {
		ko.Status.State = nil
	}
	if resp.CoreNetwork.Tags != nil {
		f9 := []*svcapitypes.Tag{}
		for _, f9iter := range resp.CoreNetwork.Tags {
			f9elem := &svcapitypes.Tag{}
			if f9iter.Key != nil {
				f9elem.Key = f9iter.Key
			}
			if f9iter.Value != nil {
				f9elem.Value = f9iter.Value
			}
			f9 = append(f9, f9elem)
		}
		ko.Spec.Tags = f9
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	policyResp, err := rm.sdkapi.GetCoreNetworkPolicy(ctx, &svcsdk.GetCoreNetworkPolicyInput{
		CoreNetworkId: ko.Status.CoreNetworkID,
		Alias:         svcsdktypes.CoreNetworkPolicyAliasLive,
	})
	if err != nil {
		var awsErr smithy.APIError
		if !errors.As(err, &awsErr) || awsErr.ErrorCode() != "ValidationException" {
			return nil, err
		}
	}

	if policyResp != nil && policyResp.CoreNetworkPolicy != nil && policyResp.CoreNetworkPolicy.PolicyDocument != nil {
		ko.Spec.PolicyDocument = policyResp.CoreNetworkPolicy.PolicyDocument
		ko.Status.PolicyVersionID = aws.Int64(int64(*policyResp.CoreNetworkPolicy.PolicyVersionId))
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.CoreNetworkID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetCoreNetworkInput, error) {
	res := &svcsdk.GetCoreNetworkInput{}

	if r.ko.Status.CoreNetworkID != nil {
		res.CoreNetworkId = r.ko.Status.CoreNetworkID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateCoreNetworkOutput
	_ = resp
	resp, err = rm.sdkapi.CreateCoreNetwork(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateCoreNetwork", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.CoreNetwork.CoreNetworkArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.CoreNetwork.CoreNetworkArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CoreNetwork.CoreNetworkId != nil {
		ko.Status.CoreNetworkID = resp.CoreNetwork.CoreNetworkId
	} else {
		ko.Status.CoreNetworkID = nil
	}
	if resp.CoreNetwork.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CoreNetwork.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.CoreNetwork.Description != nil {
		ko.Spec.Description = resp.CoreNetwork.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.CoreNetwork.Edges != nil {
		f4 := []*svcapitypes.CoreNetworkEdge{}
		for _, f4iter := range resp.CoreNetwork.Edges {
			f4elem := &svcapitypes.CoreNetworkEdge{}
			if f4iter.Asn != nil {
				f4elem.ASN = f4iter.Asn
			}
			if f4iter.EdgeLocation != nil {
				f4elem.EdgeLocation = f4iter.EdgeLocation
			}
			if f4iter.InsideCidrBlocks != nil {
				f4elem.InsideCIDRBlocks = aws.StringSlice(f4iter.InsideCidrBlocks)
			}
			f4 = append(f4, f4elem)
		}
		ko.Status.Edges = f4
	} else {
		ko.Status.Edges = nil
	}
	if resp.CoreNetwork.GlobalNetworkId != nil {
		ko.Spec.GlobalNetworkID = resp.CoreNetwork.GlobalNetworkId
	} else {
		ko.Spec.GlobalNetworkID = nil
	}
	if resp.CoreNetwork.NetworkFunctionGroups != nil {
		f6 := []*svcapitypes.CoreNetworkNetworkFunctionGroup{}
		for _, f6iter := range resp.CoreNetwork.NetworkFunctionGroups {
			f6elem := &svcapitypes.CoreNetworkNetworkFunctionGroup{}
			if f6iter.EdgeLocations != nil {
				f6elem.EdgeLocations = aws.StringSlice(f6iter.EdgeLocations)
			}
			if f6iter.Name != nil {
				f6elem.Name = f6iter.Name
			}
			if f6iter.Segments != nil {
				f6elemf2 := &svcapitypes.ServiceInsertionSegments{}
				if f6iter.Segments.SendTo != nil {
					f6elemf2.SendTo = aws.StringSlice(f6iter.Segments.SendTo)
				}
				if f6iter.Segments.SendVia != nil {
					f6elemf2.SendVia = aws.StringSlice(f6iter.Segments.SendVia)
				}
				f6elem.Segments = f6elemf2
			}
			f6 = append(f6, f6elem)
		}
		ko.Status.NetworkFunctionGroups = f6
	} else {
		ko.Status.NetworkFunctionGroups = nil
	}
	if resp.CoreNetwork.Segments != nil {
		f7 := []*svcapitypes.CoreNetworkSegment{}
		for _, f7iter := range resp.CoreNetwork.Segments {
			f7elem := &svcapitypes.CoreNetworkSegment{}
			if f7iter.EdgeLocations != nil {
				f7elem.EdgeLocations = aws.StringSlice(f7iter.EdgeLocations)
			}
			if f7iter.Name != nil {
				f7elem.Name = f7iter.Name
			}
			if f7iter.SharedSegments != nil {
				f7elem.SharedSegments = aws.StringSlice(f7iter.SharedSegments)
			}
			f7 = append(f7, f7elem)
		}
		ko.Status.Segments = f7
	} else {
		ko.Status.Segments = nil
	}
	if resp.CoreNetwork.State != "" {
		ko.Status.State = aws.String(string(resp.CoreNetwork.State))
	} else {
		ko.Status.State = nil
	}
	if resp.CoreNetwork.Tags != nil {
		f9 := []*svcapitypes.Tag{}
		for _, f9iter := range resp.CoreNetwork.Tags {
			f9elem := &svcapitypes.Tag{}
			if f9iter.Key != nil {
				f9elem.Key = f9iter.Key
			}
			if f9iter.Value != nil {
				f9elem.Value = f9iter.Value
			}
			f9 = append(f9, f9elem)
		}
		ko.Spec.Tags = f9
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	policyResp, err := rm.sdkapi.GetCoreNetworkPolicy(ctx, &svcsdk.GetCoreNetworkPolicyInput{
		CoreNetworkId: ko.Status.CoreNetworkID,
		Alias:         svcsdktypes.CoreNetworkPolicyAliasLive,
	})
	// Immediately after creating the Core Network, the live policy may not be available yet. If we get a ResourceNotFoundException,
	// we can ignore it and assume that the policy will be available on the next read.
	if err != nil {
		var awsErr smithy.APIError
		if !errors.As(err, &awsErr) || awsErr.ErrorCode() != "ValidationException" {
			return nil, err
		}
	}

	if policyResp != nil && policyResp.CoreNetworkPolicy != nil {
		ko.Status.PolicyVersionID = aws.Int64(int64(*policyResp.CoreNetworkPolicy.PolicyVersionId))
	} else {
		ko.Status.PolicyVersionID = nil
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateCoreNetworkInput, error) {
	res := &svcsdk.CreateCoreNetworkInput{}

	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.GlobalNetworkID != nil {
		res.GlobalNetworkId = r.ko.Spec.GlobalNetworkID
	}
	if r.ko.Spec.PolicyDocument != nil {
		res.PolicyDocument = r.ko.Spec.PolicyDocument
	}
	if r.ko.Spec.Tags != nil {
		f3 := []svcsdktypes.Tag{}
		for _, f3iter := range r.ko.Spec.Tags {
			f3elem := &svcsdktypes.Tag{}
			if f3iter.Key != nil {
				f3elem.Key = f3iter.Key
			}
			if f3iter.Value != nil {
				f3elem.Value = f3iter.Value
			}
			f3 = append(f3, *f3elem)
		}
		res.Tags = f3
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		err := syncTags(
			ctx, rm.sdkapi, rm.metrics,
			string(*desired.ko.Status.ACKResourceMetadata.ARN),
			desired.ko.Spec.Tags, latest.ko.Spec.Tags,
		)
		if err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}
	if delta.DifferentAt("Spec.PolicyDocument") && desired.ko.Spec.PolicyDocument != nil {
		if err := rm.syncPolicyDocument(ctx, desired, latest); err != nil {
			return nil, err
		}
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateCoreNetworkOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateCoreNetwork(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateCoreNetwork", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.CoreNetwork.CoreNetworkArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.CoreNetwork.CoreNetworkArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CoreNetwork.CoreNetworkId != nil {
		ko.Status.CoreNetworkID = resp.CoreNetwork.CoreNetworkId
	} else {
		ko.Status.CoreNetworkID = nil
	}
	if resp.CoreNetwork.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CoreNetwork.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.CoreNetwork.Description != nil {
		ko.Spec.Description = resp.CoreNetwork.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.CoreNetwork.Edges != nil {
		f4 := []*svcapitypes.CoreNetworkEdge{}
		for _, f4iter := range resp.CoreNetwork.Edges {
			f4elem := &svcapitypes.CoreNetworkEdge{}
			if f4iter.Asn != nil {
				f4elem.ASN = f4iter.Asn
			}
			if f4iter.EdgeLocation != nil {
				f4elem.EdgeLocation = f4iter.EdgeLocation
			}
			if f4iter.InsideCidrBlocks != nil {
				f4elem.InsideCIDRBlocks = aws.StringSlice(f4iter.InsideCidrBlocks)
			}
			f4 = append(f4, f4elem)
		}
		ko.Status.Edges = f4
	} else {
		ko.Status.Edges = nil
	}
	if resp.CoreNetwork.GlobalNetworkId != nil {
		ko.Spec.GlobalNetworkID = resp.CoreNetwork.GlobalNetworkId
	} else {
		ko.Spec.GlobalNetworkID = nil
	}
	if resp.CoreNetwork.NetworkFunctionGroups != nil {
		f6 := []*svcapitypes.CoreNetworkNetworkFunctionGroup{}
		for _, f6iter := range resp.CoreNetwork.NetworkFunctionGroups {
			f6elem := &svcapitypes.CoreNetworkNetworkFunctionGroup{}
			if f6iter.EdgeLocations != nil {
				f6elem.EdgeLocations = aws.StringSlice(f6iter.EdgeLocations)
			}
			if f6iter.Name != nil {
				f6elem.Name = f6iter.Name
			}
			if f6iter.Segments != nil {
				f6elemf2 := &svcapitypes.ServiceInsertionSegments{}
				if f6iter.Segments.SendTo != nil {
					f6elemf2.SendTo = aws.StringSlice(f6iter.Segments.SendTo)
				}
				if f6iter.Segments.SendVia != nil {
					f6elemf2.SendVia = aws.StringSlice(f6iter.Segments.SendVia)
				}
				f6elem.Segments = f6elemf2
			}
			f6 = append(f6, f6elem)
		}
		ko.Status.NetworkFunctionGroups = f6
	} else {
		ko.Status.NetworkFunctionGroups = nil
	}
	if resp.CoreNetwork.Segments != nil {
		f7 := []*svcapitypes.CoreNetworkSegment{}
		for _, f7iter := range resp.CoreNetwork.Segments {
			f7elem := &svcapitypes.CoreNetworkSegment{}
			if f7iter.EdgeLocations != nil {
				f7elem.EdgeLocations = aws.StringSlice(f7iter.EdgeLocations)
			}
			if f7iter.Name != nil {
				f7elem.Name = f7iter.Name
			}
			if f7iter.SharedSegments != nil {
				f7elem.SharedSegments = aws.StringSlice(f7iter.SharedSegments)
			}
			f7 = append(f7, f7elem)
		}
		ko.Status.Segments = f7
	} else {
		ko.Status.Segments = nil
	}
	if resp.CoreNetwork.State != "" {
		ko.Status.State = aws.String(string(resp.CoreNetwork.State))
	} else {
		ko.Status.State = nil
	}
	if resp.CoreNetwork.Tags != nil {
		f9 := []*svcapitypes.Tag{}
		for _, f9iter := range resp.CoreNetwork.Tags {
			f9elem := &svcapitypes.Tag{}
			if f9iter.Key != nil {
				f9elem.Key = f9iter.Key
			}
			if f9iter.Value != nil {
				f9elem.Value = f9iter.Value
			}
			f9 = append(f9, f9elem)
		}
		ko.Spec.Tags = f9
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	ko.Status.PolicyVersionID = latest.ko.Status.PolicyVersionID
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateCoreNetworkInput, error) {
	res := &svcsdk.UpdateCoreNetworkInput{}

	if r.ko.Status.CoreNetworkID != nil {
		res.CoreNetworkId = r.ko.Status.CoreNetworkID
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteCoreNetworkOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteCoreNetwork(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteCoreNetwork", err)
	if err == nil {
		if observed, err := rm.sdkFind(ctx, r); err != ackerr.NotFound {
			if err != nil {
				return nil, err
			}
			r.SetStatus(observed)
			return r, requeueWaitWhileDeleting
		}
	}
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteCoreNetworkInput, error) {
	res := &svcsdk.DeleteCoreNetworkInput{}

	if r.ko.Status.CoreNetworkID != nil {
		res.CoreNetworkId = r.ko.Status.CoreNetworkID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.CoreNetwork,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException",
		"CoreNetworkPolicyException":
		return true
	default:
		return false
	}
}
