---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-networkmanager-reader
  namespace: default
rules:
- apiGroups:
  - networkmanager.services.k8s.aws
  resources:
  - corenetworks
  - globalnetworks
  verbs:
  - get
  - list
  - watch
