// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CoreNetworkSpec defines the desired state of CoreNetwork.
//
// Describes a core network.
type CoreNetworkSpec struct {

	// The description of a core network.
	//
	// Regex Pattern: `^[\s\S]*$`
	Description *string `json:"description,omitempty"`
	// The ID of the global network that a core network will be a part of.
	//
	// Regex Pattern: `^[\s\S]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	GlobalNetworkID  *string                                  `json:"globalNetworkID,omitempty"`
	GlobalNetworkRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"globalNetworkRef,omitempty"`
	// The policy document for creating a core network.
	//
	// Regex Pattern: `^[\s\S]*$`
	// +kubebuilder:validation:Required
	PolicyDocument *string `json:"policyDocument"`
	// Key-value tags associated with a core network request.
	Tags []*Tag `json:"tags,omitempty"`
}

// CoreNetworkStatus defines the observed state of CoreNetwork
type CoreNetworkStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The ID of a core network.
	//
	// Regex Pattern: `^core-network-([0-9a-f]{8,17})$`
	// +kubebuilder:validation:Optional
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	// The timestamp when a core network was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The edges within a core network.
	// +kubebuilder:validation:Optional
	Edges []*CoreNetworkEdge `json:"edges,omitempty"`
	// The network function groups associated with a core network.
	// +kubebuilder:validation:Optional
	NetworkFunctionGroups []*CoreNetworkNetworkFunctionGroup `json:"networkFunctionGroups,omitempty"`
	// The ID of the policy version.
	// +kubebuilder:validation:Optional
	PolicyVersionID *int64 `json:"policyVersionID,omitempty"`
	// The segments within a core network.
	// +kubebuilder:validation:Optional
	Segments []*CoreNetworkSegment `json:"segments,omitempty"`
	// The current state of a core network.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty"`
}

// CoreNetwork is the Schema for the CoreNetworks API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type CoreNetwork struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CoreNetworkSpec   `json:"spec,omitempty"`
	Status            CoreNetworkStatus `json:"status,omitempty"`
}

// CoreNetworkList contains a list of CoreNetwork
// +kubebuilder:object:root=true
type CoreNetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CoreNetwork `json:"items"`
}

func init() {
	SchemeBuilder.Register(&CoreNetwork{}, &CoreNetworkList{})
}
