// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AttachmentErrorCode string

const (
	AttachmentErrorCode_DIRECT_CONNECT_GATEWAY_EXISTING_ATTACHMENTS AttachmentErrorCode = "DIRECT_CONNECT_GATEWAY_EXISTING_ATTACHMENTS"
	AttachmentErrorCode_DIRECT_CONNECT_GATEWAY_NOT_FOUND            AttachmentErrorCode = "DIRECT_CONNECT_GATEWAY_NOT_FOUND"
	AttachmentErrorCode_DIRECT_CONNECT_GATEWAY_NO_PRIVATE_VIF       AttachmentErrorCode = "DIRECT_CONNECT_GATEWAY_NO_PRIVATE_VIF"
	AttachmentErrorCode_MAXIMUM_NO_ENCAP_LIMIT_EXCEEDED             AttachmentErrorCode = "MAXIMUM_NO_ENCAP_LIMIT_EXCEEDED"
	AttachmentErrorCode_SUBNET_DUPLICATED_IN_AVAILABILITY_ZONE      AttachmentErrorCode = "SUBNET_DUPLICATED_IN_AVAILABILITY_ZONE"
	AttachmentErrorCode_SUBNET_NOT_FOUND                            AttachmentErrorCode = "SUBNET_NOT_FOUND"
	AttachmentErrorCode_SUBNET_NO_FREE_ADDRESSES                    AttachmentErrorCode = "SUBNET_NO_FREE_ADDRESSES"
	AttachmentErrorCode_SUBNET_NO_IPV6_CIDRS                        AttachmentErrorCode = "SUBNET_NO_IPV6_CIDRS"
	AttachmentErrorCode_SUBNET_UNSUPPORTED_AVAILABILITY_ZONE        AttachmentErrorCode = "SUBNET_UNSUPPORTED_AVAILABILITY_ZONE"
	AttachmentErrorCode_VPC_NOT_FOUND                               AttachmentErrorCode = "VPC_NOT_FOUND"
	AttachmentErrorCode_VPC_UNSUPPORTED_FEATURES                    AttachmentErrorCode = "VPC_UNSUPPORTED_FEATURES"
	AttachmentErrorCode_VPN_CONNECTION_NOT_FOUND                    AttachmentErrorCode = "VPN_CONNECTION_NOT_FOUND"
	AttachmentErrorCode_VPN_EXISTING_ASSOCIATIONS                   AttachmentErrorCode = "VPN_EXISTING_ASSOCIATIONS"
)

type AttachmentState string

const (
	AttachmentState_AVAILABLE                     AttachmentState = "AVAILABLE"
	AttachmentState_CREATING                      AttachmentState = "CREATING"
	AttachmentState_DELETING                      AttachmentState = "DELETING"
	AttachmentState_FAILED                        AttachmentState = "FAILED"
	AttachmentState_PENDING_ATTACHMENT_ACCEPTANCE AttachmentState = "PENDING_ATTACHMENT_ACCEPTANCE"
	AttachmentState_PENDING_NETWORK_UPDATE        AttachmentState = "PENDING_NETWORK_UPDATE"
	AttachmentState_PENDING_TAG_ACCEPTANCE        AttachmentState = "PENDING_TAG_ACCEPTANCE"
	AttachmentState_REJECTED                      AttachmentState = "REJECTED"
	AttachmentState_UPDATING                      AttachmentState = "UPDATING"
)

type AttachmentType string

const (
	AttachmentType_CONNECT                     AttachmentType = "CONNECT"
	AttachmentType_DIRECT_CONNECT_GATEWAY      AttachmentType = "DIRECT_CONNECT_GATEWAY"
	AttachmentType_SITE_TO_SITE_VPN            AttachmentType = "SITE_TO_SITE_VPN"
	AttachmentType_TRANSIT_GATEWAY_ROUTE_TABLE AttachmentType = "TRANSIT_GATEWAY_ROUTE_TABLE"
	AttachmentType_VPC                         AttachmentType = "VPC"
)

type ChangeAction string

const (
	ChangeAction_ADD    ChangeAction = "ADD"
	ChangeAction_MODIFY ChangeAction = "MODIFY"
	ChangeAction_REMOVE ChangeAction = "REMOVE"
)

type ChangeSetState string

const (
	ChangeSetState_EXECUTING           ChangeSetState = "EXECUTING"
	ChangeSetState_EXECUTION_SUCCEEDED ChangeSetState = "EXECUTION_SUCCEEDED"
	ChangeSetState_FAILED_GENERATION   ChangeSetState = "FAILED_GENERATION"
	ChangeSetState_OUT_OF_DATE         ChangeSetState = "OUT_OF_DATE"
	ChangeSetState_PENDING_GENERATION  ChangeSetState = "PENDING_GENERATION"
	ChangeSetState_READY_TO_EXECUTE    ChangeSetState = "READY_TO_EXECUTE"
)

type ChangeStatus string

const (
	ChangeStatus_COMPLETE    ChangeStatus = "COMPLETE"
	ChangeStatus_FAILED      ChangeStatus = "FAILED"
	ChangeStatus_IN_PROGRESS ChangeStatus = "IN_PROGRESS"
	ChangeStatus_NOT_STARTED ChangeStatus = "NOT_STARTED"
)

type ChangeType string

const (
	ChangeType_ATTACHMENT_MAPPING                    ChangeType = "ATTACHMENT_MAPPING"
	ChangeType_ATTACHMENT_POLICIES_CONFIGURATION     ChangeType = "ATTACHMENT_POLICIES_CONFIGURATION"
	ChangeType_ATTACHMENT_ROUTE_PROPAGATION          ChangeType = "ATTACHMENT_ROUTE_PROPAGATION"
	ChangeType_ATTACHMENT_ROUTE_STATIC               ChangeType = "ATTACHMENT_ROUTE_STATIC"
	ChangeType_CORE_NETWORK_CONFIGURATION            ChangeType = "CORE_NETWORK_CONFIGURATION"
	ChangeType_CORE_NETWORK_EDGE                     ChangeType = "CORE_NETWORK_EDGE"
	ChangeType_CORE_NETWORK_SEGMENT                  ChangeType = "CORE_NETWORK_SEGMENT"
	ChangeType_NETWORK_FUNCTION_GROUP                ChangeType = "NETWORK_FUNCTION_GROUP"
	ChangeType_ROUTING_POLICY                        ChangeType = "ROUTING_POLICY"
	ChangeType_ROUTING_POLICY_ATTACHMENT_ASSOCIATION ChangeType = "ROUTING_POLICY_ATTACHMENT_ASSOCIATION"
	ChangeType_ROUTING_POLICY_EDGE_ASSOCIATION       ChangeType = "ROUTING_POLICY_EDGE_ASSOCIATION"
	ChangeType_ROUTING_POLICY_SEGMENT_ASSOCIATION    ChangeType = "ROUTING_POLICY_SEGMENT_ASSOCIATION"
	ChangeType_SEGMENTS_CONFIGURATION                ChangeType = "SEGMENTS_CONFIGURATION"
	ChangeType_SEGMENT_ACTIONS_CONFIGURATION         ChangeType = "SEGMENT_ACTIONS_CONFIGURATION"
)

type ConnectPeerAssociationState string

const (
	ConnectPeerAssociationState_AVAILABLE ConnectPeerAssociationState = "AVAILABLE"
	ConnectPeerAssociationState_DELETED   ConnectPeerAssociationState = "DELETED"
	ConnectPeerAssociationState_DELETING  ConnectPeerAssociationState = "DELETING"
	ConnectPeerAssociationState_PENDING   ConnectPeerAssociationState = "PENDING"
)

type ConnectPeerErrorCode string

const (
	ConnectPeerErrorCode_EDGE_LOCATION_NO_FREE_IPS    ConnectPeerErrorCode = "EDGE_LOCATION_NO_FREE_IPS"
	ConnectPeerErrorCode_EDGE_LOCATION_PEER_DUPLICATE ConnectPeerErrorCode = "EDGE_LOCATION_PEER_DUPLICATE"
	ConnectPeerErrorCode_INVALID_INSIDE_CIDR_BLOCK    ConnectPeerErrorCode = "INVALID_INSIDE_CIDR_BLOCK"
	ConnectPeerErrorCode_IP_OUTSIDE_SUBNET_CIDR_RANGE ConnectPeerErrorCode = "IP_OUTSIDE_SUBNET_CIDR_RANGE"
	ConnectPeerErrorCode_NO_ASSOCIATED_CIDR_BLOCK     ConnectPeerErrorCode = "NO_ASSOCIATED_CIDR_BLOCK"
	ConnectPeerErrorCode_SUBNET_NOT_FOUND             ConnectPeerErrorCode = "SUBNET_NOT_FOUND"
)

type ConnectPeerState string

const (
	ConnectPeerState_AVAILABLE ConnectPeerState = "AVAILABLE"
	ConnectPeerState_CREATING  ConnectPeerState = "CREATING"
	ConnectPeerState_DELETING  ConnectPeerState = "DELETING"
	ConnectPeerState_FAILED    ConnectPeerState = "FAILED"
)

type ConnectionState string

const (
	ConnectionState_AVAILABLE ConnectionState = "AVAILABLE"
	ConnectionState_DELETING  ConnectionState = "DELETING"
	ConnectionState_PENDING   ConnectionState = "PENDING"
	ConnectionState_UPDATING  ConnectionState = "UPDATING"
)

type ConnectionStatus string

const (
	ConnectionStatus_DOWN ConnectionStatus = "DOWN"
	ConnectionStatus_UP   ConnectionStatus = "UP"
)

type ConnectionType string

const (
	ConnectionType_BGP   ConnectionType = "BGP"
	ConnectionType_IPSEC ConnectionType = "IPSEC"
)

type CoreNetworkPolicyAlias string

const (
	CoreNetworkPolicyAlias_LATEST CoreNetworkPolicyAlias = "LATEST"
	CoreNetworkPolicyAlias_LIVE   CoreNetworkPolicyAlias = "LIVE"
)

type CoreNetworkState string

const (
	CoreNetworkState_AVAILABLE CoreNetworkState = "AVAILABLE"
	CoreNetworkState_CREATING  CoreNetworkState = "CREATING"
	CoreNetworkState_DELETING  CoreNetworkState = "DELETING"
	CoreNetworkState_UPDATING  CoreNetworkState = "UPDATING"
)

type CustomerGatewayAssociationState string

const (
	CustomerGatewayAssociationState_AVAILABLE CustomerGatewayAssociationState = "AVAILABLE"
	CustomerGatewayAssociationState_DELETED   CustomerGatewayAssociationState = "DELETED"
	CustomerGatewayAssociationState_DELETING  CustomerGatewayAssociationState = "DELETING"
	CustomerGatewayAssociationState_PENDING   CustomerGatewayAssociationState = "PENDING"
)

type DeviceState string

const (
	DeviceState_AVAILABLE DeviceState = "AVAILABLE"
	DeviceState_DELETING  DeviceState = "DELETING"
	DeviceState_PENDING   DeviceState = "PENDING"
	DeviceState_UPDATING  DeviceState = "UPDATING"
)

type GlobalNetworkState string

const (
	GlobalNetworkState_AVAILABLE GlobalNetworkState = "AVAILABLE"
	GlobalNetworkState_DELETING  GlobalNetworkState = "DELETING"
	GlobalNetworkState_PENDING   GlobalNetworkState = "PENDING"
	GlobalNetworkState_UPDATING  GlobalNetworkState = "UPDATING"
)

type LinkAssociationState string

const (
	LinkAssociationState_AVAILABLE LinkAssociationState = "AVAILABLE"
	LinkAssociationState_DELETED   LinkAssociationState = "DELETED"
	LinkAssociationState_DELETING  LinkAssociationState = "DELETING"
	LinkAssociationState_PENDING   LinkAssociationState = "PENDING"
)

type LinkState string

const (
	LinkState_AVAILABLE LinkState = "AVAILABLE"
	LinkState_DELETING  LinkState = "DELETING"
	LinkState_PENDING   LinkState = "PENDING"
	LinkState_UPDATING  LinkState = "UPDATING"
)

type PeeringErrorCode string

const (
	PeeringErrorCode_EDGE_LOCATION_PEER_DUPLICATE         PeeringErrorCode = "EDGE_LOCATION_PEER_DUPLICATE"
	PeeringErrorCode_INTERNAL_ERROR                       PeeringErrorCode = "INTERNAL_ERROR"
	PeeringErrorCode_INVALID_TRANSIT_GATEWAY_STATE        PeeringErrorCode = "INVALID_TRANSIT_GATEWAY_STATE"
	PeeringErrorCode_MISSING_PERMISSIONS                  PeeringErrorCode = "MISSING_PERMISSIONS"
	PeeringErrorCode_TRANSIT_GATEWAY_NOT_FOUND            PeeringErrorCode = "TRANSIT_GATEWAY_NOT_FOUND"
	PeeringErrorCode_TRANSIT_GATEWAY_PEERS_LIMIT_EXCEEDED PeeringErrorCode = "TRANSIT_GATEWAY_PEERS_LIMIT_EXCEEDED"
)

type PeeringState string

const (
	PeeringState_AVAILABLE PeeringState = "AVAILABLE"
	PeeringState_CREATING  PeeringState = "CREATING"
	PeeringState_DELETING  PeeringState = "DELETING"
	PeeringState_FAILED    PeeringState = "FAILED"
)

type PeeringType string

const (
	PeeringType_TRANSIT_GATEWAY PeeringType = "TRANSIT_GATEWAY"
)

type RouteAnalysisCompletionReasonCode string

const (
	RouteAnalysisCompletionReasonCode_BLACKHOLE_ROUTE_FOR_DESTINATION_FOUND                   RouteAnalysisCompletionReasonCode = "BLACKHOLE_ROUTE_FOR_DESTINATION_FOUND"
	RouteAnalysisCompletionReasonCode_CYCLIC_PATH_DETECTED                                    RouteAnalysisCompletionReasonCode = "CYCLIC_PATH_DETECTED"
	RouteAnalysisCompletionReasonCode_INACTIVE_ROUTE_FOR_DESTINATION_FOUND                    RouteAnalysisCompletionReasonCode = "INACTIVE_ROUTE_FOR_DESTINATION_FOUND"
	RouteAnalysisCompletionReasonCode_MAX_HOPS_EXCEEDED                                       RouteAnalysisCompletionReasonCode = "MAX_HOPS_EXCEEDED"
	RouteAnalysisCompletionReasonCode_NO_DESTINATION_ARN_PROVIDED                             RouteAnalysisCompletionReasonCode = "NO_DESTINATION_ARN_PROVIDED"
	RouteAnalysisCompletionReasonCode_POSSIBLE_MIDDLEBOX                                      RouteAnalysisCompletionReasonCode = "POSSIBLE_MIDDLEBOX"
	RouteAnalysisCompletionReasonCode_ROUTE_NOT_FOUND                                         RouteAnalysisCompletionReasonCode = "ROUTE_NOT_FOUND"
	RouteAnalysisCompletionReasonCode_TRANSIT_GATEWAY_ATTACHMENT_ATTACH_ARN_NO_MATCH          RouteAnalysisCompletionReasonCode = "TRANSIT_GATEWAY_ATTACHMENT_ATTACH_ARN_NO_MATCH"
	RouteAnalysisCompletionReasonCode_TRANSIT_GATEWAY_ATTACHMENT_NOT_FOUND                    RouteAnalysisCompletionReasonCode = "TRANSIT_GATEWAY_ATTACHMENT_NOT_FOUND"
	RouteAnalysisCompletionReasonCode_TRANSIT_GATEWAY_ATTACHMENT_NOT_IN_TRANSIT_GATEWAY       RouteAnalysisCompletionReasonCode = "TRANSIT_GATEWAY_ATTACHMENT_NOT_IN_TRANSIT_GATEWAY"
	RouteAnalysisCompletionReasonCode_TRANSIT_GATEWAY_ATTACHMENT_STABLE_ROUTE_TABLE_NOT_FOUND RouteAnalysisCompletionReasonCode = "TRANSIT_GATEWAY_ATTACHMENT_STABLE_ROUTE_TABLE_NOT_FOUND"
)

type RouteAnalysisCompletionResultCode string

const (
	RouteAnalysisCompletionResultCode_CONNECTED     RouteAnalysisCompletionResultCode = "CONNECTED"
	RouteAnalysisCompletionResultCode_NOT_CONNECTED RouteAnalysisCompletionResultCode = "NOT_CONNECTED"
)

type RouteAnalysisStatus string

const (
	RouteAnalysisStatus_COMPLETED RouteAnalysisStatus = "COMPLETED"
	RouteAnalysisStatus_FAILED    RouteAnalysisStatus = "FAILED"
	RouteAnalysisStatus_RUNNING   RouteAnalysisStatus = "RUNNING"
)

type RouteState string

const (
	RouteState_ACTIVE    RouteState = "ACTIVE"
	RouteState_BLACKHOLE RouteState = "BLACKHOLE"
)

type RouteTableType string

const (
	RouteTableType_CORE_NETWORK_SEGMENT        RouteTableType = "CORE_NETWORK_SEGMENT"
	RouteTableType_NETWORK_FUNCTION_GROUP      RouteTableType = "NETWORK_FUNCTION_GROUP"
	RouteTableType_TRANSIT_GATEWAY_ROUTE_TABLE RouteTableType = "TRANSIT_GATEWAY_ROUTE_TABLE"
)

type RouteType string

const (
	RouteType_PROPAGATED RouteType = "PROPAGATED"
	RouteType_STATIC     RouteType = "STATIC"
)

type RoutingPolicyDirection string

const (
	RoutingPolicyDirection_inbound  RoutingPolicyDirection = "inbound"
	RoutingPolicyDirection_outbound RoutingPolicyDirection = "outbound"
)

type SegmentActionServiceInsertion string

const (
	SegmentActionServiceInsertion_send_to  SegmentActionServiceInsertion = "send-to"
	SegmentActionServiceInsertion_send_via SegmentActionServiceInsertion = "send-via"
)

type SendViaMode string

const (
	SendViaMode_dual_hop   SendViaMode = "dual-hop"
	SendViaMode_single_hop SendViaMode = "single-hop"
)

type SiteState string

const (
	SiteState_AVAILABLE SiteState = "AVAILABLE"
	SiteState_DELETING  SiteState = "DELETING"
	SiteState_PENDING   SiteState = "PENDING"
	SiteState_UPDATING  SiteState = "UPDATING"
)

type TransitGatewayConnectPeerAssociationState string

const (
	TransitGatewayConnectPeerAssociationState_AVAILABLE TransitGatewayConnectPeerAssociationState = "AVAILABLE"
	TransitGatewayConnectPeerAssociationState_DELETED   TransitGatewayConnectPeerAssociationState = "DELETED"
	TransitGatewayConnectPeerAssociationState_DELETING  TransitGatewayConnectPeerAssociationState = "DELETING"
	TransitGatewayConnectPeerAssociationState_PENDING   TransitGatewayConnectPeerAssociationState = "PENDING"
)

type TransitGatewayRegistrationState string

const (
	TransitGatewayRegistrationState_AVAILABLE TransitGatewayRegistrationState = "AVAILABLE"
	TransitGatewayRegistrationState_DELETED   TransitGatewayRegistrationState = "DELETED"
	TransitGatewayRegistrationState_DELETING  TransitGatewayRegistrationState = "DELETING"
	TransitGatewayRegistrationState_FAILED    TransitGatewayRegistrationState = "FAILED"
	TransitGatewayRegistrationState_PENDING   TransitGatewayRegistrationState = "PENDING"
)

type TunnelProtocol string

const (
	TunnelProtocol_GRE      TunnelProtocol = "GRE"
	TunnelProtocol_NO_ENCAP TunnelProtocol = "NO_ENCAP"
)

type ValidationExceptionReason string

const (
	ValidationExceptionReason_CannotParse           ValidationExceptionReason = "CannotParse"
	ValidationExceptionReason_FieldValidationFailed ValidationExceptionReason = "FieldValidationFailed"
	ValidationExceptionReason_Other                 ValidationExceptionReason = "Other"
	ValidationExceptionReason_UnknownOperation      ValidationExceptionReason = "UnknownOperation"
)
